# Copyright (c) 2013 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# GNU Makefile based on shared rules provided by the Native Client SDK.
# See README.Makefiles for more details.

VALID_TOOLCHAINS := newlib pnacl

CONFIG=Debug
NACL_SDK_ROOT=$(HOME)/SDKs/nacl/pepper_31

NACL_SDK_ROOT ?= $(abspath $(CURDIR)/../..)
include $(NACL_SDK_ROOT)/tools/common.mk

# NACL_DEBUG_ENABLE=1
# PPAPI_BROWSER_DEBUG=1
# NACL_PLUGIN_DEBUG=1
# NACL_PPAPI_PROXY_DEBUG=1
# NACL_SRPC_DEBUG=255 (use a higher number for more verbose debug output)
# NACLVERBOSITY=255
# NACL_EXE_STDOUT=$(HOME)/tmp/nacl_stdout.log
# NACL_EXE_STDERR=$(HOME)/tmp/nacl_stderr.log
# NACL_EXE_STDOUT=DEBUG_ONLY:dev://postmessage
# NACL_EXE_STDERR=DEBUG_ONLY:dev://postmessage

TARGET = faces
LIBS = $(DEPS) ppapi_cpp ppapi nacl_io \
			 opencv_objdetect opencv_imgproc opencv_highgui \
			 opencv_core z \
			 jpeg png tiff

CFLAGS = -Wall -g -O0
SOURCES = faces.cpp

LDFLAGS = -pthread
CFLAGS:=$(INCLUDES)
# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

ifeq ($(CONFIG),Release)
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))
